# These are supported funding model platforms

github: openbenches # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: openbenches # Replace with a single Open Collective username
custom: https://openbenches.myspreadshop.co.uk/
